FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
     go build -mod=mod -o sandbox ./cmd/sandbox

FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/sandbox /app/sandbox

ENV PORT=8080
EXPOSE 8080

USER nonroot:nonroot
CMD ["/app/sandbox", "web", "-port", "8080", "api", "-webui_address", "https://go-ai-app-dev-216087263834.southamerica-east1.run.app", "webui", "--api_server_address", "https://go-ai-app-dev-216087263834.southamerica-east1.run.app/api"]
