FROM golang:1.25-alpine

WORKDIR /app

# Instalar git y air
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

# Ejecutar air en lugar de go run
CMD ["air", "-c", ".air.toml"]